import type { Metadata } from 'next';
import { Main } from '@styles/Main';
import Searchbar from '@components/Searchbar';
import Trending from '@components/Trending';
import Recommended from '@components/Recommended';
import SearchResults from '@components/SearchResults';

export const metadata: Metadata = {
  title: 'Entertainment Web App | Frontend Mentor Challenge',
  description: 'Generated by create next app',
};

export default function Home({
  params,
  searchParams,
}: {
  params: { slug: string };
  searchParams: { [key: string]: string | string[] | undefined };
}) {
  return (
    <Main>
      <Searchbar placeholder="Search for movies or TV series" />

      {searchParams.query ? (
        <SearchResults />
      ) : (
        <>
          <Trending />

          <Recommended />
        </>
      )}
    </Main>
  );
}
